### PR TITLE
Adhere strictly to C API naming

### PR DESCRIPTION
**Pull request by tapir**

### CODE REVIEW

**Comment by emidoots** [comment]
LGTM

**Comment by dmitshur** [comment]
Docs need updating to match new func names.

**Comment by emidoots** [comment]
Should also mention the change in the changelog.

**Comment by tapir** [comment]
I'm doing a README overhaul. I'll update all the changes. Meanwhile lets
merge this.

**Comment by dmitshur** [comment]
Reviewing this now.

**Comment by dmitshur** [comment]
LGTM.

**Pull request merged**
