### PR TITLE
API changes and support for GLFW 3.1 features.

### LINKED ISSUE #8: Go error handling
Is it better to use Go's error functionality instead of returning nil pointers?

### LINKED ISSUE #40: Change character type from uint to rune in func Window.SetCharacterCallback
It's only for code clarity. For the next API change.
Priority low. Implementation difficulty low.

### LINKED ISSUE #56: Returning errors
- GetTime should return an error.
- GLFW does not raise an error for null returns of getCurrentContext(). If no context is set as current this method will return nil.
- GetJoystickAxes should not return an error.
- GetJoystickButtons should not return an error.
- GetJoystickName should not return an error.
- GetMonitor should not return an error.
- GetAttribute should return an error.

Since these break API, they will be changed with next big revision.

### PR DESCRIPTION
**Pull request by dmitshur**
This PR contains changes from the `devel` branch. That includes minor API changes that make the API easier to use and more idiomatic, as well as support for new features of GLFW 3.1. See changelog in README for a complete list of changes.

It is planned to be merged into master when GLFW 3.1 is released.

Closes #40.
Closes #8.
Closes #56.
Closes #106.

### CODE REVIEW

**Comment by dmitshur** [comment]
image

92%! @elmindreda has been doing and awesome job and making progress.

**Comment by pwaller** [comment]
:smile:

**Comment by dmitshur** [comment]
Hey guys,

Great news! GLFW 3.1 (the C library) has been officially released today!

image

https://twitter.com/elmindreda/status/556914293984075776

I will make a PR to update this `devel_glfw3.1` branch to GLFW 3.1, and then we'll want to review this huge PR before merging it into `master`.

**Comment by pwaller** [comment]
:+1:

**Comment by dmitshur** [comment]
We are now in final review stage. This is the time to bring up any points about the **breaking** API changes that we are introducing with the 3.1 update, and make sure all potential issues and points of concern are resolved before we pull the trigger.

**_Please do not merge this PR until it has an explicit LGTM from everyone who's active in go-gl organization;**_ and let's give it at least a few days after that to make sure no more issues are raised.

Remember, this will be a breaking API change for people using the `master` version. We should be careful about that, and make sure we get it right on the first try.

**Comment by pwaller** [comment]
I wonder if we can write some gofmt/gofix style rules to make the lives of other people porting easier. We might also consider creating a glfw3-201501-legacy package or something like that so that there is a drop-in replacement for the old dependency.

**Comment by emidoots** [comment]
I'm beginning work on #118: until I have a PR in for that please don't work on anything except the README to avoid collision as that change will likely touch every `.go` file in various places.

**Comment by dmitshur** [comment]
I've finally updated all my code to the latest commit on this branch, including API changes. It was definitely a win and made my user code simpler/shorter by removing `panic(err)`, `mustBool`, `mustAction` and `, _` things.

At this time, I did not run into any instances where the removed error from API presented a problem. Thanks a lot to @slimsag for doing that PR #121!

I'll keep testing it over the next few days and report any issues I notice.

**Comment by mbertschler** [comment]
Sorry to bother you but is this ready to be merged yet or is there still some work to do?

(Just asking because I am using a glfw version with a manually patched v3.1 feature in a personal project for half a year and I would love to switch to the official package)

**Comment by tapir** [comment]
@mbertschler should be any day now. one issue left to resolve #123

**Comment by mbertschler** [comment]
@tapir Thank you!
I am really looking forward to switch to the official 3.1 which makes it possible to open source my package, because I don't want people to have to use a patched version of 3.0 just for this tool.
My package tries to provide a cross platform GUI that should make GUI programs as easy to write as a web app. (The programming model is based on [React.js](http://facebook.github.io/react/).)

**Pull request closed without merging**
