### PR TITLE
Expose *C.GLFWwindow ref. Updates #172.

### PR DESCRIPTION
**Pull request by xlab**

### CODE REVIEW

**Comment by tapir** [comment]
I would rather have this where Window is defined.

**Comment by tapir** [comment]
Also we can lose "Get". The go way is to use the name directly for getters.

**Comment by xlab** [comment]
@tapir please see the discussion in #172 
The file name has been suggested to me and we decided that `Get` should stay to keep the API consistent.

**Comment by tapir** [comment]
@xlab those functions are not getters in the sense we're talking about. They directly correspond to glfw methods with the same names. However in this case we're trying to get a reference to a private value inside Window. So it should be just GFLWWindow()

**Comment by tapir** [comment]
We can discuss it further if you like @slimsag @shurcooL

**Comment by dmitshur** [comment]
I was originally convinced by @slimsag's comment:

> > Also, style-wise, it should be GLFWWindow(), not GetGLFWWindow(). See https://golang.org/doc/effective_go.html#Getters.
> 
> @shurcooL I am well aware, but suggested the `Get` prefix because that's what we use in all three files you linked (`GetCocoaWindow`, `GetX11Window`, etc).

But now I've remembered what's going on. We kept those `Get` in order to have names that match the GLFW C API names:

http://www.glfw.org/docs/latest/group__native.html

I agree with @tapir now, since this is a pure Go construct, there's no C API to follow, we should use Go style and drop the "Get".

Also agree it doesn't deserve a new file.

**Comment by xlab** [comment]
@tapir @shurcooL yeah, I like this better.

**Pull request merged**
