### PR TITLE
Remove symbolic links when running generate-wayland-protocols.sh

### LINKED ISSUE #314: Wayland build not working because of missing symbolic link
Hi, I've been trying to use [AllenDang/giu](https://github.com/AllenDang/giu), an application framework that uses go-glfw under the hood.  
When I try to build the app using `-tags wayland` I got an error:
```
# github.com/go-gl/glfw/v3.3/glfw
In file included from /tmp/glfw/src/internal.h:190,
                 from /tmp/glfw/src/context.c:30,
                 from ./c_glfw.go:4:
/tmp/glfw/src/wl_platform.h:57:10: fatal error: wayland-xdg-shell-client-protocol.h: No such file or directory
   57 | #include "wayland-xdg-shell-client-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

In the wiki I found that i should use `scripts/generate-wayland-protocols.sh`, which successfully compiled this repository.

But that didn't solve my problem, because I need to run the script for the library that I downloaded via `go get`.

Where should I run the script? and do I make it permanent so it doesn't get overridden by updates?

### PR DESCRIPTION
**Pull request by santiagocezar**
According to https://github.com/golang/go/issues/24057#issuecomment-377430635, Go modules do not support symbolic links.

It modifies the script so it removes the wayland-xdg-decoration-client-protocol.h link created by wayland-scanner when running generate-wayland-protocols.sh. It also regenerates the protocol files using the new script.

This pull request fixes #314.

### CODE REVIEW

**Comment by pwaller** [comment]
Thanks for looking into this and finding a fix.

It looks like something has gone a bit wrong though, please take a look at the [travis log](https://travis-ci.org/github/go-gl/glfw/jobs/766224873). If this goes green, it's an easy accept.

**Comment by santiagocezar** [comment]
> ```
> HEAD detached at FETCH_HEAD
> Changes not staged for commit:
>  (use "git add <file>..." to update what will be committed)
>  (use "git restore <file>..." to discard changes in working directory)
>	modified:   v3.2/glfw/glfw/src/wayland-idle-inhibit-unstable-v1-client-protocol.h
>	modified:   v3.2/glfw/glfw/src/wayland-pointer-constraints-unstable-v1-client-protocol.h
>	modified:   v3.2/glfw/glfw/src/wayland-relative-pointer-unstable-v1-client-protocol.h
>	modified:   v3.2/glfw/glfw/src/wayland-viewporter-client-protocol.h
>	modified:   v3.2/glfw/glfw/src/wayland-xdg-decoration-client-protocol.h
>	modified:   v3.2/glfw/glfw/src/wayland-xdg-shell-client-protocol.h
>	modified:   v3.3/glfw/glfw/src/wayland-idle-inhibit-unstable-v1-client-protocol.h
>	modified:   v3.3/glfw/glfw/src/wayland-pointer-constraints-unstable-v1-client-protocol.h
>	modified:   v3.3/glfw/glfw/src/wayland-relative-pointer-unstable-v1-client-protocol.h
>	modified:   v3.3/glfw/glfw/src/wayland-viewporter-client-protocol.h
>	modified:   v3.3/glfw/glfw/src/wayland-xdg-decoration-client-protocol.h
>	modified:   v3.3/glfw/glfw/src/wayland-xdg-shell-client-protocol.h
>	modified:   v3.3/glfw/glfw_tree_rebuild.go
> ```

I can't reproduce this on my machine, looks like travis is using a version different to the one I have of the wayland tools, producing differences when generating the source files. Though I'm not sure how the glfw_tree_rebuild.go file gets modified.

I don't have an Ubuntu machine to test the build, so I don't know how to proceed.

**Comment by pwaller** [comment]
Thanks for giving a good go at it.

> I can't reproduce this on my machine, looks like travis is using a version different to the one I have of the wayland tools, producing differences when generating the source files.

Ah, this is unfortunate. Of course, if you don't have the same version of the wayland tools you won't necessarily end up with the same headers. I do not know if this is a significant problem or not. Looking at the diff in the build, it seems it is OK, the only difference being some #ifdef include guards which have been introduced on Ubuntu but not your system.

> Though I'm not sure how the glfw_tree_rebuild.go file gets modified.

This is modified by 'go generate' (run in CI) and represents a hash of the sources, so if there is a diff, the hash will be different.

It looks to me like you should be able to take the diff as it appears in travis and paste it into `patch -p1` run from the root of the repository. That should bring your sources inline with what travis expects. Please can you have a go at this? If you get stuck I can do it for you - if you need that please [allow edits from maintainers](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on your PR so I can verify travis is green before merging.

The purpose of this check in Travis here is to ensure that what's committed in the repo is consistent with a version running in CI, to make sure everything is consistent with being autogenerated (and that we don't accidentally diverge from upstream).

**Comment by santiagocezar** [comment]
Thank you so much! Your suggestion worked, I hope this can be merged now.

**Pull request merged**
