### PR TITLE
Add easily runnable examples

### PR DESCRIPTION
**Pull request by egonelbre**
Add minimal examples that can be used to test basic functionality.

### CODE REVIEW

**Review by dmitshur — COMMENTED** [review]
I think the distinction between example and test is that a test is intended for developers of a package, and an example is intended for users. Since this is primarily a test, I suggest using that term.

Specifically, how about renaming v3.3/glfw/example/main.go to v3.3/glfw/test/customcursor.go, and adding a "//go:build test" constraint, so it doesn't show up when listing packages while still being easy to run by a developer with `go run customcursor.go`.

Another comment, I think it's generally fine for us to maintain and develop only v3.3 (or whichever is the latest and actively used), and leave v3.2 and v3.1 as is. This is mostly for the future, it's not a big deal either way in this PR. Thanks.

**Comment by egonelbre** [comment]
Ah, maybe in that case I'll put it in `glfw/testdata/customcursor/main.go`? AFAIR `testdata` is hidden by default and usually I avoid build tags, because they mean bunch of tooling won't work on the files.

**Comment by dmitshur** [comment]
That seems fine too.

> usually I avoid build tags, because they mean bunch of tooling won't work on the files

My hope is that work on issues like golang/go#29202 and golang/go#57979 will make this less of a problem over time.

**Comment by egonelbre** [comment]
I did the changes.

But, yes, improvements at the tooling level would be great.

**Comment by egonelbre** [comment]
@dmitshur tiny ping

**Review by dmitshur — APPROVED** [review]
Thanks.

**Pull request merged**
