### PR TITLE
Update `devel_glfw3.1` branch to official GLFW 3.1 release.

### PR DESCRIPTION
**Pull request by dmitshur**
See glfw/glfw@4188c263e31ec3d5da99a77d939ab56bc199fda6.

Just a simple update as described in the [wiki](https://github.com/go-gl/glfw3/wiki/Development#updating-glfw-c-source). Seems to compile and work okay.

Let's merge this into `devel_glfw3.1` branch quickly, and begin reviewing that entire branch.

### CODE REVIEW

**Comment by dmitshur** [comment]
Actually, I'll make one change to the steps, that is to remove the remaining CMake files from the src folder since they are unused. See https://github.com/go-gl/glfw3/wiki/Development/_compare/f020363355d32d30879c44455340fb8b246f5eb5...bb7f409a63f3e1010447238264bf1874a3dff1d5.

**Comment by dmitshur** [comment]
I've added some commits to resolve merge conflict and revert PR #101. It was needed to be done on `master`, but its change is no longer needed for GLFW 3.1. This will hopefully make the `devel_glfw3.1` branch mergeable into `master` again.

**Comment by dmitshur** [comment]
I think this PR-into-PR is ready to be merged now.

**Comment by emidoots** [comment]
All very straight-forward. LGTM.

**Pull request merged**
